<?php

return [
    'users' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'roles' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'academic-sessions' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'activate',
    ],
    'classes' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'subjects',
    ],
    'sections' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'students' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
        'import',
        'enrollment',
        'promote',
    ],
    'subjects' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'subject-teachers' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'section-teachers' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'room-teachers' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'attendance' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'tasks',
        'roster',
    ],
    'fee-categories' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'fee-structures' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'fee-assignments' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'fee-vouchers' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'generate',
    ],
    'fees' => [
        'ledger',
        'student-vouchers',
        'collect',
    ],
    'timetable' => [
        'list',
        'read',
        'update',
        'delete',
        'generate',
        'setup',
        'export',
        'swap',
    ],
    'institute' => [
        'read',
        'update',
        'activate',
    ],
    'subscription' => [
        'read',
        'upgrade',
        'invoice',
        'payment',
    ],
    'notifications' => [
        'list',
        'read',
        'delete',
    ],
    'dashboard' => [
        'read',
    ],
];
